apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: kubeflow  # or your target namespace
spec:
  accessModes:
    - ReadWriteMany   # Or ReadWriteOnce, depending on your storage
  resources:
    requests:
      storage: 1Gi     # Adjust size as needed
  storageClassName: standard  # Use the correct StorageClass for your cluster
